### ISSUE TITLE
device disconnect

### ISSUE THREAD

**Issue by babayoussef** [siliconwitchery/s1-micropython#1]
when I type FPGA.read(rx) the device is disconnected.
also help() function is not recognized and the API cant get micropython version.

I can flash the fpga using s1-blink-demo, I found some warning in the fpga side (I modify the .pcf file and .v file, no warning any more), in the c sdk side some warning still existe but the flash passed and the led blink. And I can change the blinking rate. 

I like the S1 module, great job.

I use the S1 Popout with J-Link mini on a Macbook air M1

**Comment by siliconwitch** [comment]
Thanks for your nice words! 🙂

Could you send me the exact steps which caused the crash? When I test here it seems okay:

```python
>>> import machine
>>> rx = bytearray(10)
>>> machine.FPGA.read(rx)
>>> rx
bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
```

Regarding the `help()` command, it's currently removed because the memory was running a bit little low. I'm waiting for a big new MicroPython release and will do some upgrades to all of this. That should improve a lot of things

**Comment by babayoussef** [comment]
Thank you for your time. I checked it today on two modules and it seems to be ok.
